### 👉👉👉 JWT login 👈👈👈

# @name jwt_login
POST http://localhost:3000/jwt/login
Content-Type: application/json

{
  "email": "admin@user.com",
  "password": "admin"
}

###

@token = {{ jwt_login.response.body.token }}

### 👉👉👉 Session login 👈👈👈

POST http://localhost:3000/session/login
Content-Type: application/json

{
  "email": "admin@user.com",
  "password": "admin"
}

###
POST http://localhost:3000/session/logout


### 👉👉👉 Customer Endpoints 👈👈👈

# @name createCustomer
POST http://localhost:3000/customers
Content-Type: application/json

{
  "name": "john_doe",
  "email": "john@example.com",
  "password": "securepassword",
  "phone": "1234567890",
  "address": "123 Main St"
}

###

@customer_id = {{ createCustomer.response.body.id }}

### Get a customer by ID
GET http://localhost:3000/admin/customers/{{ customer_id }}
Authorization: Bearer {{ token }}

### List customers in admin with pagination and optional filtering
GET http://localhost:3000/admin/customers?page=1&limit=10
Authorization: Bearer {{ token }}

### Update a customer
PATCH http://localhost:3000/admin/customers/{{ customer_id }}
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "password": "newpassword",
  "phone": "0987654321",
  "address": "456 Elm St"
}

### Delete a customer
DELETE http://localhost:3000/admin/customers/{{ customer_id }}
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "id": 1
}

### 👉👉👉 Category Endpoints 👈👈👈

# @name createCategory
POST http://localhost:3000/admin/categories
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "name": "Category Name",
  "slug": "category-slug"
}

###
@category_id = {{ createCategory.response.body.id }}
@category_slug = {{ createCategory.response.body.slug }}

### Get a category by slug
GET http://localhost:3000/categories/{{ category_slug }}

### List categories with pagination and optional filtering
GET http://localhost:3000/categories?page=1&limit=10&name=Category

### List categories in admin with pagination and optional filtering
GET http://localhost:3000/admin/categories?page=1&limit=10&name=Category
Authorization: Bearer {{ token }}

### Update a category
PATCH http://localhost:3000/admin/categories/{{ category_id }}
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "name": "Updated Category Name",
  "slug": "updated-category-slug"
}

### Delete a category
DELETE http://localhost:3000/admin/categories/{{ category_id }}
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "id": "{{ category_id }}"
}


### 👉👉👉 Product Endpoints 👈👈👈

# @name createProduct
POST http://localhost:3000/admin/products
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "name": "Product Name",
  "slug": "product-slug",
  "description": "Product Description",
  "price": 100,
  "categoryIds": [ "{{ category_id }}" ]
}

###
@product_id = {{ createProduct.response.body.data.id }}
@product_slug = {{ createProduct.response.body.data.slug }}

### Get a product by ID
GET http://localhost:3000/admin/products/{{ product_id }}
Authorization: Bearer {{ token }}

### Get a product by slug
GET http://localhost:3000/products/{{ product_slug }}

### Update a product
PATCH http://localhost:3000/admin/products/{{ product_id }}
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "id": "{{ product_id }}",
  "name": "Updated Product Name",
  "slug": "{{ product_slug }}",
  "description": "Updated Product Description",
  "price": 150,
  "categoryIds": [ "{{ category_id }}" ]
}

### Delete a product
DELETE http://localhost:3000/admin/products/{{ product_id }}
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "id": "{{ product_id }}"
}

### List products with pagination and optional filtering&name=Product&categories_slug=category-slug,xpto1,xpto2
GET http://localhost:3000/products?page=1&limit=10

### List products in admin with pagination and optional filtering &name=Product&categories_slug=category-slug&user_id=1
GET http://localhost:3000/admin/products?page=1&limit=10
Authorization: Bearer {{ token }}

### Get csv of products
GET http://localhost:3000/admin/products.csv
Authorization: Bearer {{ token }}

### 👉👉👉 Cart Endpoints 👈👈👈

### Create a cart

# @name createCart
POST http://localhost:3000/carts

###

@cart_uuid = {{ createCart.response.body.uuid }}

### Add an item to the cart "customerId": "{{ customer_id }}",
# @name addItemToCart
POST http://localhost:3000/carts/{{cart_uuid}}/items
Content-Type: application/json

{
  "productId": "{{ product_id }}",
  "quantity": 1
}

###

@cart_id = {{ addItemToCart.response.body.id }}

### Get a cart by ID
GET http://localhost:3000/carts/{{ cart_uuid }}

### Remove an item from the cart
DELETE http://localhost:3000/carts/{{cart_uuid}}/items/1
Content-Type: application/json

{
  "cartItemId": 1
}

### Clear the cart
POST http://localhost:3000/carts/{{cart_uuid}}/clear

### 👉👉👉 Order Endpoints 👈👈👈

### Create an order
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "payment_method": "CREDIT_CARD",
  "cart_uuid": "{{ cart_uuid }}"
}

### List orders with pagination and optional filtering
GET http://localhost:3000/orders?page=1&limit=10
Authorization: Bearer {{ token }}