services:
  # Atualize o nome do serviço que você deseja utilizar
  app:
    # Caso queira sobrescrever o Dockerfile do serviço para utilizar o da pasta .devcontainer,
    # descomente as linhas abaixo. Lembre que o caminho do Dockerfile e do context é relativo
    # ao arquivo docker-compose.yml principal (o primeiro listado no "dockerComposeFile"
    # do devcontainer.json). O exemplo abaixo pressupõe que o arquivo principal está na raiz do projeto.
    #
    # build:
    #   context: .
    #   dockerfile: .devcontainer/Dockerfile

    volumes:
      # Atualize para o local onde o VS Code deve montar a pasta do seu projeto
      - .:/home/node/app:cached

    # Caso utilize depuradores baseados em ptrace (C++, Go, Rust), descomente as linhas abaixo:
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Caso queira que o container não seja finalizado imediatamente, descomente a linha abaixo:
    # command: sleep infinity
